zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
ribbon:
  ReadTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
        timeout:
          enabled: false
# Increase the timeout for communiction with the reprot serive so it doesn't die during report generation
pwr-report-service:
  ribbon:
    ReadTimeout: 600000 # 60 seconds should suffice
    ConnectTimeout: 10000
#  Same for profile. Also report related
pwr-profile-service:
  ribbon:
    ReadTimeout: 20000
    ConnectTimeout: 10000