server:
  port: 9000
pwr:
  url:
    skill: http://pwr-skill-service:9003
    profile: http://pwr-profile-service:9004
    report: http://pwr-report-service:9005
    view-profile: http://pwr-view-profile-service:9008
    statistics: http://pwr-statistics-service:9007
---
spring:
  config:
    activate:
      on-profile: localDev
pwr:
  url:
    skill: http://localhost:9003
    profile: http://localhost:9004
    report: http://localhost:9005
    view-profile: http://localhost:9008
    statistics: http://localhost:9009
logging:
  level:
    org:
      springframework:
        security: DEBUG
