server:
  port: 9000
pwr:
  url:
    skill: http://pwr-skill-service:9003
    profile: http://pwr-profile-service:9004
    report: http://pwr-report-service:9005
    view-profile: http://pwr-view-profile-service:9008
    statistics: http://pwr-statistics-service:9007
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: <oauth issuer uri>
